version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: src/CQRS.API/Dockerfile
    image: "damdavidprieto/cqrs-api"
    container_name: "cqrs-api"
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    environment: # defined for run.sh to access the ports
      - HTTP_PORT=${HTTP_PORT}
      - HTTPS_PORT=${HTTPS_PORT}
    env_file:
      - src/CQRS.API/list.env
    volumes:
      - ~/.aspnet/https:/https:ro
      - db-data:/app/Data
      - ./src/CQRS.API/run.sh:/app/run.sh:ro
    entrypoint: ["/bin/sh", "/app/run.sh"]

volumes:
  db-data: