namespace BankService_Domain.Models;

/// <summary>
/// code auto generated by this command :
/// Scaffold-DbContext "Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\Users\julio\source\repos\PTANetBackMVC\BankService\BankService_Domain\DataBase\BankServiceDB.mdf;Integrated Security=True" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models
/// on EF issue on .NET framework
/// </summary>
public partial class Bank
{
    public int Id { get; set; }

    public string Name { get; set; } = null!;

    public string Bic { get; set; } = null!;

    public string Country { get; set; } = null!;
}
