/************************************************************************************************************
 * Julio's tech test for Alicunde Job position
 ************************************************************************************************************/


namespace BankService_Domain.Models;

using Microsoft.EntityFrameworkCore;

/// <summary>
/// code auto generated by this command :
/// Scaffold-DbContext "Data Source=LAPTOP-0PL7RF4D\\SQLEXPRESS;Initial Catalog=BankServiceDB;Integrated Security=True;Trust Server Certificate=True" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Models
/// on EF issue on .NET framework
/// </summary>
public partial class BankservicedbMdfContext : DbContext
{
    public BankservicedbMdfContext()
    {
    }

    public BankservicedbMdfContext(DbContextOptions<BankservicedbMdfContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Bank> Banks { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer("Data Source=LAPTOP-0PL7RF4D\\SQLEXPRESS;Initial Catalog=BankServiceDB;Integrated Security=True;Trust Server Certificate=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Bank>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Banks__3214EC07FDF7E745");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Bic)
                .HasMaxLength(20)
                .IsFixedLength();
            entity.Property(e => e.Country)
                .HasMaxLength(2)
                .HasDefaultValue("NO")
                .IsFixedLength();
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsFixedLength();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
