USE [master]
GO

/****** Object:  Database [BankServiceDB]    Script Date: 5/17/2024 11:28:30 AM ******/
CREATE DATABASE [BankServiceDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BankServiceDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BankServiceDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BankServiceDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\BankServiceDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BankServiceDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BankServiceDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BankServiceDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BankServiceDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BankServiceDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BankServiceDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [BankServiceDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BankServiceDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BankServiceDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BankServiceDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BankServiceDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BankServiceDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BankServiceDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BankServiceDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BankServiceDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BankServiceDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BankServiceDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BankServiceDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BankServiceDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BankServiceDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BankServiceDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BankServiceDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BankServiceDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BankServiceDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BankServiceDB] SET  MULTI_USER 
GO

ALTER DATABASE [BankServiceDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BankServiceDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BankServiceDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BankServiceDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BankServiceDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BankServiceDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BankServiceDB] SET  READ_WRITE 
GO


